# --- Параметры запуска ---

# Система должна запрашивать диапазон дат (yes). Вариант "no" - система определяет последнюю дату в основном файле и пишет диапазон до дня, предыдущего текущему (вчера)
date_range: yes

# Записывать в файл scv (yes/no)
write_to_csv: no

# Путь к файлу csv
path_csv: csv/
